"""Shared structural typing helpers for CLI mixins.

These protocols describe the host interfaces expected by extracted mixin
modules. They keep mixins type-friendly without introducing runtime coupling.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class SlashCommandsHost(Protocol):
    def _command_project_root(self) -> Path: ...
    def _parse_diff_args(self, parsed: Any) -> tuple[str, list[str]] | None: ...
    def _run_git_diff(self, git_args: list[str], cwd: Path) -> str | None: ...


class ActionRenderersHost(Protocol):
    _reasoning: Any
    _cli_tool_icons: Any
    _pending_shell_action: tuple[str, str] | None
    _pending_shell_command: str | None
    _pending_shell_title: str | None
    _pending_shell_is_internal: bool
    _pending_activity_card: Any
    _pending_finish_text: str | None
    _pending_finish_renderable: Any | None
    _last_terminal_input_sent: str
    _last_notice_error_content: Any
    _orient_burst_count: int
    _orient_burst_area: str

    def refresh(self) -> None: ...
    def _apply_reasoning_text(self, *a: Any, **kw: Any) -> Any: ...
    def _stop_reasoning(self, *a: Any, **kw: Any) -> Any: ...
    def _ensure_reasoning(self, *a: Any, **kw: Any) -> Any: ...
    def _clear_streaming_preview(self, *a: Any, **kw: Any) -> Any: ...
    def _flush_pending_tool_cards(self, *a: Any, **kw: Any) -> Any: ...
    def _flush_pending_activity_card(self, *a: Any, **kw: Any) -> Any: ...
    def _flush_pending_shell_action(self, *a: Any, **kw: Any) -> Any: ...
    def _flush_orient_burst(self, *a: Any, **kw: Any) -> Any: ...
    def _handle_streaming_chunk(self, *a: Any, **kw: Any) -> Any: ...
    def _print_or_buffer(self, *a: Any, **kw: Any) -> Any: ...
    def _emit_activity_turn_header(self, *a: Any, **kw: Any) -> Any: ...
    def _append_assistant_message(self, *a: Any, **kw: Any) -> Any: ...
    def _append_history(self, *a: Any, **kw: Any) -> Any: ...
    def _buffer_pending_activity(self, *a: Any, **kw: Any) -> Any: ...
    def _print_activity(self, *a: Any, **kw: Any) -> Any: ...
    def _set_task_panel(self, *a: Any, **kw: Any) -> Any: ...
    def _reset_delegate_panel(self, *a: Any, **kw: Any) -> Any: ...
    def _render_tool_sourced_think(self, *a: Any, **kw: Any) -> Any: ...


class ObservationRenderersHost(Protocol):
    _console: Any
    _hud: Any
    _reasoning: Any
    _pending_activity_card: Any
    _pending_shell_command: str | None
    _pending_shell_action: tuple[str, str] | None
    _pending_shell_title: str | None
    _pending_shell_is_internal: bool
    _delegate_workers: Any
    _delegate_batch_id: Any
    _stream_fallback_count: Any
    _last_notice_error_content: Any
    _last_retry_status_signature: Any
    _last_terminal_input_sent: str

    def refresh(self) -> None: ...
    def _apply_reasoning_text(self, *a: Any, **kw: Any) -> Any: ...
    def _stop_reasoning(self, *a: Any, **kw: Any) -> Any: ...
    def _ensure_reasoning(self, *a: Any, **kw: Any) -> Any: ...
    def _flush_pending_activity_card(self, *a: Any, **kw: Any) -> Any: ...
    def _flush_pending_tool_cards(self, *a: Any, **kw: Any) -> Any: ...
    def _clear_streaming_preview(self, *a: Any, **kw: Any) -> Any: ...
    def _print_or_buffer(self, *a: Any, **kw: Any) -> Any: ...
    def _emit_activity_turn_header(self, *a: Any, **kw: Any) -> Any: ...
    def _append_history(self, *a: Any, **kw: Any) -> Any: ...
    def _take_pending_activity_card(self, *a: Any, **kw: Any) -> Any: ...
    def _render_pending_activity_card(self, *a: Any, **kw: Any) -> Any: ...
    def _set_delegate_panel(self, *a: Any, **kw: Any) -> Any: ...
    def _set_task_panel(self, *a: Any, **kw: Any) -> Any: ...
    def _reset_pending_shell(self, *a: Any, **kw: Any) -> Any: ...
    def _consume_pending_shell(self, *a: Any, **kw: Any) -> Any: ...
    def _render_status_content(self, *a: Any, **kw: Any) -> Any: ...
    def _handle_delegate_progress_status(self, *a: Any, **kw: Any) -> Any: ...
    def _handle_retry_status(self, *a: Any, **kw: Any) -> Any: ...
    def _delegate_batch_mismatch(self, *a: Any, **kw: Any) -> Any: ...
    def _delegate_worker_record(self, *a: Any, **kw: Any) -> Any: ...
    def _coerce_positive_int(self, *a: Any, **kw: Any) -> Any: ...
    def _strip_pty_echo_if_pending(self, *a: Any, **kw: Any) -> Any: ...
    def _render_terminal_panel(self, *a: Any, **kw: Any) -> Any: ...
