"""Shared structural typing helpers for CLI mixins.

These protocols describe the host interfaces expected by extracted mixin
modules. They keep mixins type-friendly without introducing runtime coupling.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class RunHelpersHost(Protocol):
    _config: Any
    _memory: Any
    _runtime: Any
    _agent: Any
    _llm_registry: Any
    _conversation_stats: Any
    _pt_session: Any
    _renderer: Any
    _console: Any
    _hud: Any
    _reasoning: Any
    _pending_resume: str | None
    _next_action: Any
    _last_user_message: str | None
    _prompt_ctrl_c_hint_shown: bool

    def _create_prompt_session(self) -> Any: ...
    def _set_footer_system_line(self, text: str, *, kind: str = 'info') -> None: ...
    async def _read_non_interactive_input(self) -> Any: ...
    def _handle_parsed_command(self, *args: Any, **kwargs: Any) -> Any: ...
    def _cancel_agent(self, *args: Any, **kwargs: Any) -> Any: ...
    def _resume_session(self, *args: Any, **kwargs: Any) -> Any: ...
    def _wait_for_agent_idle(self, *args: Any, **kwargs: Any) -> Any: ...
    def _sync_terminal_after_agent_turn(self, *args: Any, **kwargs: Any) -> Any: ...
    def _invalidate_pt(self) -> None: ...
    def _warn(self, msg: str) -> None: ...


class SlashCommandsHost(Protocol):
    def _command_project_root(self) -> Path: ...
    def _parse_diff_args(self, parsed: Any) -> tuple[str, list[str]] | None: ...
    def _run_git_diff(self, git_args: list[str], cwd: Path) -> str | None: ...


class SessionLifecycleHost(Protocol):
    _memory: Any
    _runtime: Any
    _agent: Any
    _llm_registry: Any
    _conversation_stats: Any
    _event_stream: Any
    _acquire_result: Any
    _renderer: Any
    _console: Any
    _hud: Any
    _reasoning: Any


class ActionRenderersHost(Protocol):
    _reasoning: Any
    _cli_tool_icons: Any
    _pending_shell_action: tuple[str, str] | None
    _pending_shell_command: str | None
    _pending_shell_title: str | None
    _pending_shell_is_internal: bool
    _pending_activity_card: Any

    def refresh(self) -> None: ...
    def _apply_reasoning_text(self, *a: Any, **kw: Any) -> Any: ...
    def _stop_reasoning(self, *a: Any, **kw: Any) -> Any: ...
    def _ensure_reasoning(self, *a: Any, **kw: Any) -> Any: ...
    def _clear_streaming_preview(self, *a: Any, **kw: Any) -> Any: ...
    def _flush_pending_tool_cards(self, *a: Any, **kw: Any) -> Any: ...
    def _flush_pending_activity_card(self, *a: Any, **kw: Any) -> Any: ...
    def _flush_pending_shell_action(self, *a: Any, **kw: Any) -> Any: ...
    def _handle_streaming_chunk(self, *a: Any, **kw: Any) -> Any: ...
    def _print_or_buffer(self, *a: Any, **kw: Any) -> Any: ...
    def _emit_activity_turn_header(self, *a: Any, **kw: Any) -> Any: ...
    def _append_assistant_message(self, *a: Any, **kw: Any) -> Any: ...
    def _append_history(self, *a: Any, **kw: Any) -> Any: ...
    def _buffer_pending_activity(self, *a: Any, **kw: Any) -> Any: ...
    def _print_activity(self, *a: Any, **kw: Any) -> Any: ...
    def _set_task_panel(self, *a: Any, **kw: Any) -> Any: ...
    def _reset_delegate_panel(self, *a: Any, **kw: Any) -> Any: ...


class ObservationRenderersHost(Protocol):
    _console: Any
    _hud: Any
    _reasoning: Any
    _pending_activity_card: Any
    _pending_shell_command: str | None
    _pending_shell_action: tuple[str, str] | None
    _pending_shell_title: str | None
    _delegate_workers: Any
    _delegate_batch_id: Any
    _stream_fallback_count: Any

    def refresh(self) -> None: ...
    def _apply_reasoning_text(self, *a: Any, **kw: Any) -> Any: ...
    def _stop_reasoning(self, *a: Any, **kw: Any) -> Any: ...
    def _ensure_reasoning(self, *a: Any, **kw: Any) -> Any: ...
    def _flush_pending_activity_card(self, *a: Any, **kw: Any) -> Any: ...
    def _flush_pending_tool_cards(self, *a: Any, **kw: Any) -> Any: ...
    def _clear_streaming_preview(self, *a: Any, **kw: Any) -> Any: ...
    def _print_or_buffer(self, *a: Any, **kw: Any) -> Any: ...
    def _emit_activity_turn_header(self, *a: Any, **kw: Any) -> Any: ...
    def _append_history(self, *a: Any, **kw: Any) -> Any: ...
    def _take_pending_activity_card(self, *a: Any, **kw: Any) -> Any: ...
    def _render_pending_activity_card(self, *a: Any, **kw: Any) -> Any: ...
    def _set_delegate_panel(self, *a: Any, **kw: Any) -> Any: ...
    def _set_task_panel(self, *a: Any, **kw: Any) -> Any: ...
