"""Centralized visual theme tokens for Grinta CLI.

All color and style constants used across CLI components are defined here.
Import from this module instead of scattering raw hex values through files.

Naming conventions
------------------

* ``CLR_*_BODY`` — soft, low-saturation tone meant for body text inside a
  panel (kept legible against the terminal background without shouting).
* ``CLR_*_ICON`` — bright, bold companion tone used for inline status icons,
  badges, or single-character markers (``✓``, ``✗``, ``•``, ``ℹ``).

Always pair the body and icon tones from the same family to keep panels
visually coherent across components.

Package layout
--------------

* ``env`` — NO_COLOR, preset selection, accessibility flags
* ``tokens`` — Rich / prompt_toolkit color constants (mutable by presets)
* ``navy`` — Textual TUI navy palette
* ``presets`` — preset override application
* ``styles`` — Rich and prompt_toolkit style builders
"""

from __future__ import annotations

from backend.cli.theme.env import (
    accessible_mode_enabled,
    get_theme_preset,
    no_color_enabled,
    set_theme_preset,
    splash_anim_disabled,
    use_ascii_cli_symbols,
)
from backend.cli.theme.presets import apply_theme_overrides, sync_theme_aliases

apply_theme_overrides()
sync_theme_aliases()

from backend.cli.theme.navy import (  # noqa: E402
    NAVY_BG,
    NAVY_BG_NOTICE,
    NAVY_BG_TRANSCRIPT_ACTIVE,
    NAVY_BG_TRANSCRIPT_BLOCK,
    NAVY_BG_USER,
    NAVY_BORDER,
    NAVY_BORDER_BRIGHT,
    NAVY_BORDER_HIGHLIGHT,
    NAVY_BORDER_INPUT,
    NAVY_BORDER_INPUT_FOCUS,
    NAVY_BRAND,
    NAVY_BRAND_DIM,
    NAVY_BUTTON_BG,
    NAVY_BUTTON_BG_HOVER,
    NAVY_BUTTON_BORDER_BOTTOM,
    NAVY_BUTTON_BORDER_TOP,
    NAVY_BUTTON_PRIMARY_BG,
    NAVY_BUTTON_PRIMARY_BORDER_TOP,
    NAVY_BUTTON_PRIMARY_HOVER,
    NAVY_DIVIDER,
    NAVY_DOMAIN_MCP,
    NAVY_DOMAIN_MCP_DIM,
    NAVY_DOMAIN_SKILLS,
    NAVY_DOMAIN_SKILLS_DIM,
    NAVY_ERROR,
    NAVY_FOCUS_ACCENT,
    NAVY_GREEN_ACCENT,
    NAVY_HUD_SELECT_AUTONOMY,
    NAVY_HUD_SELECT_AUTONOMY_FOCUS,
    NAVY_HUD_SELECT_AUTONOMY_OVERLAY,
    NAVY_HUD_SELECT_MODE,
    NAVY_HUD_SELECT_MODE_FOCUS,
    NAVY_HUD_SELECT_MODE_OVERLAY,
    NAVY_HUD_SELECT_REASONING,
    NAVY_HUD_SELECT_REASONING_FOCUS,
    NAVY_HUD_SELECT_REASONING_OVERLAY,
    NAVY_LOADING,
    NAVY_MODAL_BG,
    NAVY_MODAL_OVERLAY,
    NAVY_OPTION_HIGHLIGHTED,
    NAVY_OPTION_HIGHLIGHTED_TEXT,
    NAVY_OPTION_HOVER,
    NAVY_OPTION_HOVER_TEXT,
    NAVY_PROGRESS_BAR,
    NAVY_PROGRESS_BG,
    NAVY_PROGRESS_COMPLETE,
    NAVY_PURPLE_ACCENT,
    NAVY_READY,
    NAVY_RED_ACCENT,
    NAVY_RUNNING,
    NAVY_RUNNING_DIM,
    NAVY_SCROLLBAR_ACTIVE,
    NAVY_SCROLLBAR_HOVER,
    NAVY_SCROLLBAR_THUMB,
    NAVY_SCROLLBAR_TRACK,
    NAVY_SPARKLINE_MAX,
    NAVY_SPARKLINE_MIN,
    NAVY_SURFACE,
    NAVY_SURFACE_RISING,
    NAVY_SURFACE_TOP,
    NAVY_TEXT_BODY,
    NAVY_TEXT_DIM,
    NAVY_TEXT_LIVE,
    NAVY_TEXT_LIVE_ACTIVE,
    NAVY_TEXT_MUTED,
    NAVY_TEXT_NOTICE,
    NAVY_TEXT_PRIMARY,
    NAVY_TEXT_SECONDARY,
    NAVY_TEXT_TERTIARY,
    NAVY_TEXT_USER,
    NAVY_WAITING,
    NAVY_WAITING_DIM,
    NAVY_YELLOW_ACCENT,
)
from backend.cli.theme.styles import (  # noqa: E402
    grinta_rich_theme_styles,
    prompt_toolkit_style_dict,
)
from backend.cli.theme.tokens import (  # noqa: E402
    CLR_ACTION,
    CLR_AUTONOMY_BALANCED,
    CLR_AUTONOMY_CONSERVATIVE,
    CLR_AUTONOMY_FULL,
    CLR_BRAND,
    CLR_BRAND_HUE,
    CLR_CARD_BORDER,
    CLR_CARD_TITLE,
    CLR_DECISION_BORDER,
    CLR_DETAIL,
    CLR_DIFF_ADD,
    CLR_DIFF_ADD_DIM,
    CLR_DIFF_REM,
    CLR_DIFF_REM_DIM,
    CLR_DRAFT_BORDER,
    CLR_ERR_BODY,
    CLR_ERR_ICON,
    CLR_ERROR_BODY,
    CLR_ERROR_PIPE,
    CLR_ERROR_PREFIX,
    CLR_HUD_DETAIL,
    CLR_HUD_MODEL,
    CLR_INFO_BODY,
    CLR_INFO_ICON,
    CLR_LIVE_PANEL_BORDER,
    CLR_META,
    CLR_MUTED_TEXT,
    CLR_NOTICE_BG,
    CLR_NOTICE_TEXT,
    CLR_OK_BODY,
    CLR_OK_ICON,
    CLR_OPTION_RECOMMENDED,
    CLR_OPTION_TEXT,
    CLR_ORIENT_GUTTER,
    CLR_OUTPUT_PANEL_BORDER,
    CLR_OUTPUT_PANEL_TITLE,
    CLR_QUESTION_TEXT,
    CLR_REASONING_COMMITTED,
    CLR_REASONING_SNAP,
    CLR_RECOVERY_HINT,
    CLR_RECOVERY_HINT_DIM,
    CLR_RISK_ASK,
    CLR_RISK_HIGH,
    CLR_RISK_LOW,
    CLR_RISK_MEDIUM,
    CLR_SECONDARY,
    CLR_SECONDARY_ERR,
    CLR_SECONDARY_OK,
    CLR_SEP,
    CLR_SHELL_BORDER,
    CLR_SHELL_OUTPUT,
    CLR_SPINNER,
    CLR_SPLASH_FIGLET,
    CLR_SPLASH_LOGO_ACCENT,
    CLR_STATE_RUNNING,
    CLR_STATUS_ERR,
    CLR_STATUS_OK,
    CLR_STATUS_WARN,
    CLR_THINKING_BORDER,
    CLR_THOUGHT_BODY,
    CLR_TURN_RULE,
    CLR_USER_BG,
    CLR_USER_BORDER,
    CLR_VERB,
    CLR_WARN_BODY,
    CLR_WARN_ICON,
    CLR_WORKER_ACTION,
    CLR_WORKER_BORDER,
    CLR_WORKER_LABEL,
    CLR_WORKER_LABEL_DONE,
    CLR_WORKER_LABEL_FAILED,
    CLR_WORKER_SPINNER,
    CLR_WORKER_TIMER,
    HUD_BG,
    MARK_ERR,
    MARK_INFO,
    MARK_OK,
    MARK_PROMPT,
    MARK_WARN,
    MSG_STYLE_PROVIDER_HINT,
    MSG_STYLE_SUCCESS_MARK,
    PT_COMPLETION_MENU_BG,
    PT_COMPLETION_MENU_CURRENT,
    PT_COMPLETION_META_BG,
    PT_COMPLETION_META_CURRENT,
    PT_DEFAULT_FG,
    PT_FOOTER_BADGE_BRACKET,
    PT_FOOTER_BADGE_CORE,
    PT_FOOTER_KICKER,
    PT_FOOTER_WARN_BRACKET,
    PT_FOOTER_WARN_CORE,
    PT_FOOTER_WARN_KICKER,
    PT_FOOTER_WARN_SEP,
    PT_PLACEHOLDER_DIM,
    PT_SCROLLBAR_BG,
    PT_SCROLLBAR_BUTTON,
    STYLE_BOLD,
    STYLE_BOLD_DIM,
    STYLE_DEFAULT,
    STYLE_DELEGATE_DONE,
    STYLE_DELEGATE_FAILED,
    STYLE_DELEGATE_RUNNING,
    STYLE_DELEGATE_STARTING,
    STYLE_DIM,
    STYLE_EMPTY,
    STYLE_ITALIC_DIM,
    STYLE_SYSTEM_TAG_AUTONOMY,
    STYLE_SYSTEM_TAG_NOTE,
    STYLE_SYSTEM_TAG_SETTINGS,
    STYLE_SYSTEM_TAG_STATUS,
    STYLE_SYSTEM_TAG_SYSTEM,
    STYLE_SYSTEM_TAG_TIMEOUT,
    STYLE_SYSTEM_TAG_WARNING,
)


def mark_ok() -> str:
    return '+' if use_ascii_cli_symbols() else MARK_OK


def mark_err() -> str:
    return 'x' if use_ascii_cli_symbols() else MARK_ERR


def mark_warn() -> str:
    return '!' if use_ascii_cli_symbols() else MARK_WARN


def mark_info() -> str:
    return '*' if use_ascii_cli_symbols() else MARK_INFO


def mark_prompt() -> str:
    return '>' if use_ascii_cli_symbols() else MARK_PROMPT


def get_grinta_pygments_style() -> type:
    """Get or create the Grinta Pygments style for syntax highlighting."""
    from backend.cli.theme.syntax_theme import build_grinta_pygments_style

    return build_grinta_pygments_style()


__all__ = [
    'CLR_ACTION',
    'CLR_AUTONOMY_BALANCED',
    'CLR_AUTONOMY_CONSERVATIVE',
    'CLR_AUTONOMY_FULL',
    'CLR_BRAND',
    'CLR_BRAND_HUE',
    'CLR_CARD_BORDER',
    'CLR_CARD_TITLE',
    'CLR_DECISION_BORDER',
    'CLR_DETAIL',
    'CLR_DIFF_ADD',
    'CLR_DIFF_ADD_DIM',
    'CLR_DIFF_REM',
    'CLR_DIFF_REM_DIM',
    'CLR_DRAFT_BORDER',
    'CLR_ERR_BODY',
    'CLR_ERR_ICON',
    'CLR_ERROR_BODY',
    'CLR_ERROR_PIPE',
    'CLR_ERROR_PREFIX',
    'CLR_HUD_DETAIL',
    'CLR_HUD_MODEL',
    'CLR_INFO_BODY',
    'CLR_INFO_ICON',
    'CLR_LIVE_PANEL_BORDER',
    'CLR_META',
    'CLR_MUTED_TEXT',
    'CLR_NOTICE_BG',
    'CLR_NOTICE_TEXT',
    'CLR_OK_BODY',
    'CLR_OK_ICON',
    'CLR_OPTION_RECOMMENDED',
    'CLR_OPTION_TEXT',
    'CLR_ORIENT_GUTTER',
    'CLR_OUTPUT_PANEL_BORDER',
    'CLR_OUTPUT_PANEL_TITLE',
    'CLR_QUESTION_TEXT',
    'CLR_REASONING_COMMITTED',
    'CLR_REASONING_SNAP',
    'CLR_RECOVERY_HINT',
    'CLR_RECOVERY_HINT_DIM',
    'CLR_RISK_ASK',
    'CLR_RISK_HIGH',
    'CLR_RISK_LOW',
    'CLR_RISK_MEDIUM',
    'CLR_SECONDARY',
    'CLR_SECONDARY_ERR',
    'CLR_SECONDARY_OK',
    'CLR_SEP',
    'CLR_SHELL_BORDER',
    'CLR_SHELL_OUTPUT',
    'CLR_SPINNER',
    'CLR_SPLASH_FIGLET',
    'CLR_SPLASH_LOGO_ACCENT',
    'CLR_STATE_RUNNING',
    'CLR_STATUS_ERR',
    'CLR_STATUS_OK',
    'CLR_STATUS_WARN',
    'CLR_THINKING_BORDER',
    'CLR_THOUGHT_BODY',
    'CLR_TURN_RULE',
    'CLR_USER_BG',
    'CLR_USER_BORDER',
    'CLR_VERB',
    'CLR_WARN_BODY',
    'CLR_WARN_ICON',
    'CLR_WORKER_ACTION',
    'CLR_WORKER_BORDER',
    'CLR_WORKER_LABEL',
    'CLR_WORKER_LABEL_DONE',
    'CLR_WORKER_LABEL_FAILED',
    'CLR_WORKER_SPINNER',
    'CLR_WORKER_TIMER',
    'HUD_BG',
    'MARK_ERR',
    'MARK_INFO',
    'MARK_OK',
    'MARK_PROMPT',
    'MARK_WARN',
    'MSG_STYLE_PROVIDER_HINT',
    'MSG_STYLE_SUCCESS_MARK',
    'NAVY_BG',
    'NAVY_BG_NOTICE',
    'NAVY_BG_TRANSCRIPT_ACTIVE',
    'NAVY_BG_TRANSCRIPT_BLOCK',
    'NAVY_BG_USER',
    'NAVY_BORDER',
    'NAVY_BORDER_BRIGHT',
    'NAVY_BORDER_HIGHLIGHT',
    'NAVY_BORDER_INPUT',
    'NAVY_BORDER_INPUT_FOCUS',
    'NAVY_BRAND',
    'NAVY_BRAND_DIM',
    'NAVY_BUTTON_BG',
    'NAVY_BUTTON_BG_HOVER',
    'NAVY_BUTTON_BORDER_BOTTOM',
    'NAVY_BUTTON_BORDER_TOP',
    'NAVY_BUTTON_PRIMARY_BG',
    'NAVY_BUTTON_PRIMARY_BORDER_TOP',
    'NAVY_BUTTON_PRIMARY_HOVER',
    'NAVY_DIVIDER',
    'NAVY_DOMAIN_MCP',
    'NAVY_DOMAIN_MCP_DIM',
    'NAVY_DOMAIN_SKILLS',
    'NAVY_DOMAIN_SKILLS_DIM',
    'NAVY_ERROR',
    'NAVY_FOCUS_ACCENT',
    'NAVY_GREEN_ACCENT',
    'NAVY_HUD_SELECT_AUTONOMY',
    'NAVY_HUD_SELECT_AUTONOMY_FOCUS',
    'NAVY_HUD_SELECT_AUTONOMY_OVERLAY',
    'NAVY_HUD_SELECT_MODE',
    'NAVY_HUD_SELECT_MODE_FOCUS',
    'NAVY_HUD_SELECT_MODE_OVERLAY',
    'NAVY_HUD_SELECT_REASONING',
    'NAVY_HUD_SELECT_REASONING_FOCUS',
    'NAVY_HUD_SELECT_REASONING_OVERLAY',
    'NAVY_LOADING',
    'NAVY_MODAL_BG',
    'NAVY_MODAL_OVERLAY',
    'NAVY_OPTION_HIGHLIGHTED',
    'NAVY_OPTION_HIGHLIGHTED_TEXT',
    'NAVY_OPTION_HOVER',
    'NAVY_OPTION_HOVER_TEXT',
    'NAVY_PROGRESS_BAR',
    'NAVY_PROGRESS_BG',
    'NAVY_PROGRESS_COMPLETE',
    'NAVY_PURPLE_ACCENT',
    'NAVY_READY',
    'NAVY_RED_ACCENT',
    'NAVY_RUNNING',
    'NAVY_RUNNING_DIM',
    'NAVY_SCROLLBAR_ACTIVE',
    'NAVY_SCROLLBAR_HOVER',
    'NAVY_SCROLLBAR_THUMB',
    'NAVY_SCROLLBAR_TRACK',
    'NAVY_SPARKLINE_MAX',
    'NAVY_SPARKLINE_MIN',
    'NAVY_SURFACE',
    'NAVY_SURFACE_RISING',
    'NAVY_SURFACE_TOP',
    'NAVY_TEXT_BODY',
    'NAVY_TEXT_DIM',
    'NAVY_TEXT_LIVE',
    'NAVY_TEXT_LIVE_ACTIVE',
    'NAVY_TEXT_MUTED',
    'NAVY_TEXT_NOTICE',
    'NAVY_TEXT_PRIMARY',
    'NAVY_TEXT_SECONDARY',
    'NAVY_TEXT_TERTIARY',
    'NAVY_TEXT_USER',
    'NAVY_TEXT_MUTED',
    'NAVY_TEXT_PRIMARY',
    'NAVY_TEXT_SECONDARY',
    'NAVY_TEXT_TERTIARY',
    'NAVY_WAITING',
    'NAVY_WAITING_DIM',
    'NAVY_YELLOW_ACCENT',
    'PT_COMPLETION_MENU_BG',
    'PT_COMPLETION_MENU_CURRENT',
    'PT_COMPLETION_META_BG',
    'PT_COMPLETION_META_CURRENT',
    'PT_DEFAULT_FG',
    'PT_FOOTER_BADGE_BRACKET',
    'PT_FOOTER_BADGE_CORE',
    'PT_FOOTER_KICKER',
    'PT_FOOTER_WARN_BRACKET',
    'PT_FOOTER_WARN_CORE',
    'PT_FOOTER_WARN_KICKER',
    'PT_FOOTER_WARN_SEP',
    'PT_PLACEHOLDER_DIM',
    'PT_SCROLLBAR_BG',
    'PT_SCROLLBAR_BUTTON',
    'STYLE_BOLD',
    'STYLE_BOLD_DIM',
    'STYLE_DEFAULT',
    'STYLE_DELEGATE_DONE',
    'STYLE_DELEGATE_FAILED',
    'STYLE_DELEGATE_RUNNING',
    'STYLE_DELEGATE_STARTING',
    'STYLE_DIM',
    'STYLE_EMPTY',
    'STYLE_ITALIC_DIM',
    'STYLE_SYSTEM_TAG_AUTONOMY',
    'STYLE_SYSTEM_TAG_NOTE',
    'STYLE_SYSTEM_TAG_SETTINGS',
    'STYLE_SYSTEM_TAG_STATUS',
    'STYLE_SYSTEM_TAG_SYSTEM',
    'STYLE_SYSTEM_TAG_TIMEOUT',
    'STYLE_SYSTEM_TAG_WARNING',
    'accessible_mode_enabled',
    'get_grinta_pygments_style',
    'get_theme_preset',
    'grinta_rich_theme_styles',
    'mark_err',
    'mark_info',
    'mark_ok',
    'mark_prompt',
    'mark_warn',
    'no_color_enabled',
    'prompt_toolkit_style_dict',
    'set_theme_preset',
    'splash_anim_disabled',
    'use_ascii_cli_symbols',
]
