"""Theme preset overrides applied at import time."""

from __future__ import annotations

from backend.cli.theme.env import get_theme_preset
import backend.cli.theme.tokens as tokens


def apply_theme_overrides() -> None:
    """Mutate token constants based on the active preset."""
    preset = get_theme_preset()
    if preset in ('default', 'dark'):
        return

    if preset == 'light':
        tokens.CLR_CARD_BORDER = '#6b8ba0'
        tokens.CLR_META = '#5a7285'
        tokens.CLR_BRAND = 'bold #0369a1'
        tokens.CLR_BRAND_HUE = '#0369a1'
        tokens.CLR_STATUS_OK = '#15803d'
        tokens.CLR_STATUS_WARN = '#b45309'
        tokens.CLR_STATUS_ERR = '#b91c1c'
        tokens.CLR_HUD_MODEL = 'bold #0f172a'
        tokens.CLR_HUD_DETAIL = '#334155'
        tokens.CLR_OK_BODY = '#15803d'
        tokens.CLR_OK_ICON = 'bold #166534'
        tokens.CLR_ERR_BODY = '#b91c1c'
        tokens.CLR_ERR_ICON = 'bold #991b1b'
        tokens.CLR_WARN_BODY = '#b45309'
        tokens.CLR_WARN_ICON = 'bold #92400e'
        tokens.CLR_INFO_BODY = '#1d4ed8'
        tokens.CLR_INFO_ICON = 'bold #1e40af'
        tokens.CLR_SEP = '#64748b'
        tokens.CLR_CARD_TITLE = 'bold #1e293b'
        tokens.CLR_THINKING_BORDER = '#94a3b8'
        tokens.CLR_LIVE_PANEL_BORDER = '#cbd5e1'
        tokens.CLR_THOUGHT_BODY = '#64748b'
        tokens.CLR_SECTION_RULE = '#94a3b8'
        tokens.CLR_RISK_HIGH = 'bold #dc2626'
        tokens.CLR_RISK_MEDIUM = '#ca8a04'
        tokens.CLR_RISK_LOW = '#16a34a'
        tokens.CLR_SPLASH_FIGLET = 'bold #b91c1c'
        tokens.CLR_SPLASH_LOGO_ACCENT = '#b91c1c'
        tokens.CLR_ORIENT_GUTTER = '#64748b'
        tokens.STYLE_BOLD_DIM = 'bold #475569'
        tokens.CLR_USER_BG = 'on #f8fafc'

    elif preset == 'high-contrast':
        tokens.CLR_CARD_BORDER = 'white'
        tokens.CLR_META = 'white'
        tokens.CLR_BRAND = 'bold white'
        tokens.CLR_BRAND_HUE = 'white'
        tokens.CLR_STATUS_OK = 'bold green'
        tokens.CLR_STATUS_WARN = 'bold yellow'
        tokens.CLR_STATUS_ERR = 'bold red'
        tokens.CLR_HUD_MODEL = 'bold white'
        tokens.CLR_HUD_DETAIL = 'white'
        tokens.CLR_OK_BODY = 'green'
        tokens.CLR_OK_ICON = 'bold green'
        tokens.CLR_ERR_BODY = 'red'
        tokens.CLR_ERR_ICON = 'bold red'
        tokens.CLR_WARN_BODY = 'yellow'
        tokens.CLR_WARN_ICON = 'bold yellow'
        tokens.CLR_INFO_BODY = 'cyan'
        tokens.CLR_INFO_ICON = 'bold cyan'
        tokens.CLR_SEP = 'white'
        tokens.CLR_CARD_TITLE = 'bold white'
        tokens.CLR_THINKING_BORDER = 'white'
        tokens.CLR_LIVE_PANEL_BORDER = 'bright_black'
        tokens.CLR_THOUGHT_BODY = 'bright_black'
        tokens.CLR_SECTION_RULE = 'white'
        tokens.CLR_RISK_HIGH = 'bold red'
        tokens.CLR_RISK_MEDIUM = 'bold yellow'
        tokens.CLR_RISK_LOW = 'bold green'
        tokens.CLR_SPLASH_FIGLET = 'bold white'
        tokens.CLR_SPLASH_LOGO_ACCENT = 'white'
        tokens.CLR_ORIENT_GUTTER = 'bright_black'
        tokens.STYLE_BOLD_DIM = 'bold white'
        tokens.CLR_USER_BG = ''

    elif preset == 'ocean':
        tokens.CLR_CARD_BORDER = '#4895d6'
        tokens.CLR_META = '#7eb8da'
        tokens.CLR_BRAND = 'bold #00b4d8'
        tokens.CLR_BRAND_HUE = '#00b4d8'
        tokens.CLR_STATUS_OK = '#2dd4bf'
        tokens.CLR_STATUS_WARN = '#fbbf24'
        tokens.CLR_STATUS_ERR = '#fb7185'
        tokens.CLR_HUD_MODEL = 'bold #e0f2fe'
        tokens.CLR_HUD_DETAIL = '#bae6fd'
        tokens.CLR_OK_BODY = '#5eead4'
        tokens.CLR_OK_ICON = 'bold #14b8a6'
        tokens.CLR_ERR_BODY = '#fda4af'
        tokens.CLR_ERR_ICON = 'bold #f43f5e'
        tokens.CLR_WARN_BODY = '#fde047'
        tokens.CLR_WARN_ICON = 'bold #eab308'
        tokens.CLR_INFO_BODY = '#7dd3fc'
        tokens.CLR_INFO_ICON = 'bold #0ea5e9'
        tokens.CLR_SEP = '#6b9fc4'
        tokens.CLR_CARD_TITLE = 'bold #bae6fd'
        tokens.CLR_THINKING_BORDER = '#3b82f6'
        tokens.CLR_LIVE_PANEL_BORDER = '#1e3a5f'
        tokens.CLR_THOUGHT_BODY = '#6096b4'
        tokens.CLR_SECTION_RULE = '#3b82f6'
        tokens.CLR_RISK_HIGH = 'bold #f43f5e'
        tokens.CLR_RISK_MEDIUM = '#eab308'
        tokens.CLR_RISK_LOW = '#22d3ee'
        tokens.CLR_SPLASH_FIGLET = 'bold #0ea5e9'
        tokens.CLR_SPLASH_LOGO_ACCENT = '#0ea5e9'
        tokens.CLR_ORIENT_GUTTER = '#4a7a9a'
        tokens.STYLE_BOLD_DIM = 'bold #7dd3fc'
        tokens.CLR_USER_BG = 'on #0f1c2e'

    elif preset == 'mono':
        tokens.CLR_CARD_BORDER = 'bright_black'
        tokens.CLR_META = 'bright_black'
        tokens.CLR_BRAND = 'bold white'
        tokens.CLR_BRAND_HUE = 'white'
        tokens.CLR_STATUS_OK = 'green'
        tokens.CLR_STATUS_WARN = 'yellow'
        tokens.CLR_STATUS_ERR = 'red'
        tokens.CLR_HUD_MODEL = 'bold white'
        tokens.CLR_HUD_DETAIL = 'white'
        tokens.CLR_OK_BODY = 'green'
        tokens.CLR_OK_ICON = 'bold green'
        tokens.CLR_ERR_BODY = 'red'
        tokens.CLR_ERR_ICON = 'bold red'
        tokens.CLR_WARN_BODY = 'yellow'
        tokens.CLR_WARN_ICON = 'bold yellow'
        tokens.CLR_INFO_BODY = 'cyan'
        tokens.CLR_INFO_ICON = 'bold cyan'
        tokens.CLR_SEP = 'bright_black'
        tokens.CLR_CARD_TITLE = 'bold white'
        tokens.CLR_THINKING_BORDER = 'bright_black'
        tokens.CLR_LIVE_PANEL_BORDER = 'bright_black'
        tokens.CLR_THOUGHT_BODY = 'bright_black'
        tokens.CLR_SECTION_RULE = 'bright_black'
        tokens.CLR_RISK_HIGH = 'bold red'
        tokens.CLR_RISK_MEDIUM = 'bold yellow'
        tokens.CLR_RISK_LOW = 'bold green'
        tokens.CLR_SPLASH_FIGLET = 'bold white'
        tokens.CLR_SPLASH_LOGO_ACCENT = 'white'
        tokens.CLR_ORIENT_GUTTER = 'bright_black'
        tokens.STYLE_BOLD_DIM = 'bold white'
        tokens.CLR_USER_BG = ''

    elif preset == 'deep-system-instrumentation':
        tokens.CLR_CARD_BORDER = '#1b233a'
        tokens.CLR_META = '#969aad'
        tokens.CLR_BRAND = 'bold #91abec'
        tokens.CLR_BRAND_HUE = '#91abec'
        tokens.CLR_STATUS_OK = '#54efae'
        tokens.CLR_STATUS_WARN = '#f6ff8f'
        tokens.CLR_STATUS_ERR = '#fd8383'
        tokens.CLR_HUD_MODEL = 'bold #e9e9e9'
        tokens.CLR_HUD_DETAIL = '#969aad'
        tokens.CLR_OK_BODY = '#54efae'
        tokens.CLR_OK_ICON = 'bold #54efae'
        tokens.CLR_ERR_BODY = '#fd8383'
        tokens.CLR_ERR_ICON = 'bold #fd8383'
        tokens.CLR_WARN_BODY = '#f6ff8f'
        tokens.CLR_WARN_ICON = 'bold #f6ff8f'
        tokens.CLR_INFO_BODY = '#91abec'
        tokens.CLR_INFO_ICON = 'bold #91abec'
        tokens.CLR_SEP = '#1b233a'
        tokens.CLR_CARD_TITLE = 'bold #91abec'
        tokens.CLR_THINKING_BORDER = '#1b233a'
        tokens.CLR_LIVE_PANEL_BORDER = '#1b233a'
        tokens.CLR_THOUGHT_BODY = '#65737e'
        tokens.CLR_SECTION_RULE = '#32416a'
        tokens.CLR_RISK_HIGH = 'bold #fd8383'
        tokens.CLR_RISK_MEDIUM = '#f6ff8f'
        tokens.CLR_RISK_LOW = '#54efae'
        tokens.CLR_SPLASH_FIGLET = 'bold #91abec'
        tokens.CLR_SPLASH_LOGO_ACCENT = '#91abec'
        tokens.CLR_VERB = 'bold #91abec'
        tokens.CLR_DETAIL = '#e9e9e9'
        tokens.CLR_SECONDARY = '#969aad'
        tokens.CLR_SECONDARY_OK = 'dim #54efae'
        tokens.CLR_SECONDARY_ERR = 'dim #fd8383'
        tokens.CLR_DIFF_ADD = '#54efae'
        tokens.CLR_DIFF_REM = '#fd8383'
        tokens.CLR_DIFF_ADD_DIM = 'dim #54efae'
        tokens.CLR_DIFF_REM_DIM = 'dim #fd8383'
        tokens.MSG_STYLE_SUCCESS_MARK = 'bold #54efae'
        tokens.MSG_STYLE_PROVIDER_HINT = '#91abec'
        tokens.STYLE_SYSTEM_TAG_WARNING = '#f6ff8f'
        tokens.STYLE_SYSTEM_TAG_AUTONOMY = '#91abec'
        tokens.STYLE_SYSTEM_TAG_STATUS = '#54efae'
        tokens.STYLE_SYSTEM_TAG_SETTINGS = '#91abec'
        tokens.STYLE_SYSTEM_TAG_SYSTEM = '#91abec'
        tokens.STYLE_SYSTEM_TAG_TIMEOUT = '#f6ff8f'
        tokens.STYLE_SYSTEM_TAG_NOTE = '#91abec'
        tokens.STYLE_DELEGATE_STARTING = '#91abec'
        tokens.STYLE_DELEGATE_RUNNING = '#f6ff8f'
        tokens.STYLE_DELEGATE_DONE = '#54efae'
        tokens.STYLE_DELEGATE_FAILED = '#fd8383'
        tokens.CLR_WORKER_SPINNER = '#91abec'
        tokens.CLR_WORKER_TIMER = '#969aad'
        tokens.CLR_WORKER_LABEL = 'bold #e9e9e9'
        tokens.CLR_WORKER_ACTION = '#969aad'
        tokens.CLR_WORKER_LABEL_DONE = 'bold #54efae'
        tokens.CLR_WORKER_LABEL_FAILED = 'bold #fd8383'
        tokens.CLR_WORKER_BORDER = '#1b233a'
        tokens.CLR_SPINNER = '#91abec'
        tokens.CLR_ACTION = 'bold #e9e9e9'
        tokens.CLR_DRAFT_BORDER = '#91abec'
        tokens.CLR_DECISION_BORDER = '#f6ff8f'
        tokens.CLR_USER_BORDER = 'dim #91abec'
        tokens.CLR_USER_BG = 'on #111b29'
        tokens.CLR_STATE_RUNNING = '#91abec bold'
        tokens.CLR_AUTONOMY_BALANCED = '#54efae'
        tokens.CLR_AUTONOMY_FULL = '#f6ff8f bold'
        tokens.CLR_AUTONOMY_CONSERVATIVE = '#91abec bold'
        tokens.CLR_QUESTION_TEXT = '#f6ff8f'
        tokens.CLR_OPTION_TEXT = '#e9e9e9'
        tokens.CLR_OPTION_RECOMMENDED = '#f6ff8f'
        tokens.CLR_OUTPUT_PANEL_BORDER = '#1b233a'
        tokens.CLR_OUTPUT_PANEL_TITLE = 'dim #969aad'
        tokens.CLR_RECOVERY_HINT = '#91abec'
        tokens.CLR_RECOVERY_HINT_DIM = 'dim #91abec'
        tokens.CLR_ORIENT_GUTTER = '#5a6a8a'
        tokens.STYLE_BOLD_DIM = 'bold #969aad'
        tokens.CLR_MUTED_TEXT = '#1b233a'
        tokens.PT_DEFAULT_FG = '#e9e9e9'
        tokens.PT_PLACEHOLDER_DIM = '#1b233a'
        tokens.PT_FOOTER_BADGE_BRACKET = '#1b233a'
        tokens.PT_FOOTER_BADGE_CORE = 'bold #91abec'
        tokens.PT_FOOTER_KICKER = 'bold #91abec'
        tokens.PT_FOOTER_WARN_BRACKET = '#3d1f1f'
        tokens.PT_FOOTER_WARN_CORE = 'bold #f6ff8f'
        tokens.PT_FOOTER_WARN_KICKER = 'bold #f6ff8f'
        tokens.PT_FOOTER_WARN_SEP = '#3d1f1f'
        tokens.PT_COMPLETION_MENU_BG = 'bg:#060a14 #969aad'
        tokens.PT_COMPLETION_MENU_CURRENT = 'bg:#1b233a bold #91abec'
        tokens.PT_COMPLETION_META_BG = 'bg:#060a14 #969aad'
        tokens.PT_COMPLETION_META_CURRENT = 'bg:#1b233a #91abec'
        tokens.PT_SCROLLBAR_BG = 'bg:#060a14'
        tokens.PT_SCROLLBAR_BUTTON = 'bg:#1b233a'


def sync_theme_aliases() -> None:
    """Keep legacy theme aliases aligned after preset overrides."""
    tokens.CLR_REASONING_SNAP = tokens.CLR_THOUGHT_BODY
    tokens.CLR_REASONING_COMMITTED = tokens.CLR_THOUGHT_BODY
