"""Quick-start configuration generator for new Forge users.

Generates a minimal ``config.toml`` with only the settings that matter
on day one.  Every other knob inherits sensible defaults.

Usage (CLI)::

    python -m backend.core.config.quickstart

Usage (programmatic)::

    from backend.core.config.quickstart import generate_quickstart_config
    toml_str = generate_quickstart_config(
        api_key="sk-...",
        model="claude-sonnet-4-20250514",
    )

"""

from __future__ import annotations

import os
import textwrap
from pathlib import Path

# ------------------------------------------------------------------ #
# Minimal config template                                             #
# ------------------------------------------------------------------ #

_QUICKSTART_TEMPLATE = textwrap.dedent("""\
    # Forge — Quick-start configuration
    # Generated by `forge config init`
    # Full reference: config.template.toml

    [core]
    # Maximum LLM spend (USD) per task — prevents runaway costs
    max_budget_per_task = {max_budget}

    [llm]
    # Your LLM provider API key
    api_key = "{api_key}"

    # Model to use (e.g. claude-sonnet-4-20250514, gpt-4o, etc.)
    model = "{model}"
    {base_url_line}

    [agent]
    # Tools enabled by default — adjust as needed
    enable_browsing = true
    enable_editor = true
    enable_cmd = true
""")


def generate_quickstart_config(
    api_key: str = "",
    model: str = "claude-sonnet-4-20250514",
    base_url: str = "",
    max_budget: float = 5.0,
) -> str:
    """Return a minimal TOML config string ready to write to ``config.toml``."""
    base_url_line = f'base_url = "{base_url}"' if base_url else '# base_url = ""'
    return _QUICKSTART_TEMPLATE.format(
        api_key=api_key,
        model=model,
        base_url_line=base_url_line,
        max_budget=max_budget,
    )


def _interactive_init(dest: Path) -> None:
    """Walk the user through creating a minimal config file."""
    print("🔧 Forge Quick-Start Configuration")
    print("=" * 40)
    print()

    if dest.exists():
        overwrite = input(f"  {dest} already exists. Overwrite? [y/N] ").strip().lower()
        if overwrite != "y":
            print("  Aborted.")
            return

    api_key = input("  LLM API key (leave blank to set later): ").strip()
    model = (
        input("  Model [claude-sonnet-4-20250514]: ").strip()
        or "claude-sonnet-4-20250514"
    )
    base_url = input("  Base URL (blank for default): ").strip()
    budget_str = input("  Max budget per task in USD [5.0]: ").strip()
    max_budget = float(budget_str) if budget_str else 5.0

    content = generate_quickstart_config(
        api_key=api_key,
        model=model,
        base_url=base_url,
        max_budget=max_budget,
    )

    dest.write_text(content, encoding="utf-8")
    print(f"\n  ✅ Config written to {dest}")
    print("  📖 See config.template.toml for all available settings.\n")


# ------------------------------------------------------------------ #
# CLI entrypoint                                                      #
# ------------------------------------------------------------------ #


def main() -> None:
    """CLI entry-point: ``python -m backend.core.config.quickstart``."""
    # Determine project root (where config.toml lives)
    project_root = Path(os.environ.get("FORGE_PROJECT_ROOT", Path.cwd()))
    dest = project_root / "config.toml"
    _interactive_init(dest)


if __name__ == "__main__":
    main()
