"""Session-level constants shared across server session modules."""

from backend.core.constants import (
    DEFAULT_SESSION_WAIT_TIME_BEFORE_CLOSE,
    DEFAULT_SESSION_WAIT_TIME_BEFORE_CLOSE_INTERVAL,
)

WAIT_TIME_BEFORE_CLOSE = DEFAULT_SESSION_WAIT_TIME_BEFORE_CLOSE
WAIT_TIME_BEFORE_CLOSE_INTERVAL = DEFAULT_SESSION_WAIT_TIME_BEFORE_CLOSE_INTERVAL
