name: Dependency Review

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Dependency review
        uses: actions/dependency-review-action@cc4f6536e38d1126c5e3b0683d469a14f23bfea4
        with:
          fail-on-severity: high
